//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleEstoque.Mensagens {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagensValidacao {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensValidacao() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControleEstoque.Mensagens.MensagensValidacao", typeof(MensagensValidacao).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {PropertyName} precisa ser fornecido..
        /// </summary>
        public static string Campo_obrigatorio {
            get {
                return ResourceManager.GetString("Campo_obrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possivel excluir a categoria por que existe vinculo com fornecedor(es).
        /// </summary>
        public static string CategoriaVinculoFornecedor {
            get {
                return ResourceManager.GetString("CategoriaVinculoFornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possivel excluir a categoria por que existe vinculo com produto(s).
        /// </summary>
        public static string CategoriaVinculoProduto {
            get {
                return ResourceManager.GetString("CategoriaVinculoProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Desconhecido entrar em contato com suporte..
        /// </summary>
        public static string ErrorDesconhecido {
            get {
                return ResourceManager.GetString("ErrorDesconhecido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedor com o Id informado não existe.
        /// </summary>
        public static string ForneceNaoEncontado {
            get {
                return ResourceManager.GetString("ForneceNaoEncontado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {PropertyName} Não é um Id Valido.
        /// </summary>
        public static string IdGuidInvalido {
            get {
                return ResourceManager.GetString("IdGuidInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id informado não corresponde ao id da classe informada!.
        /// </summary>
        public static string IdInvalido {
            get {
                return ResourceManager.GetString("IdInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possivel excluir o tipo quantidade por que existe vinculo com produto(s).
        /// </summary>
        public static string TipoQuantidadeVinculoProduto {
            get {
                return ResourceManager.GetString("TipoQuantidadeVinculoProduto", resourceCulture);
            }
        }
    }
}
